export type Cinematic3dVisualTuning = Readonly<{
  sunLightIntensity: number;
  ambientLightIntensity: number;
  sunBloomIntensity: number;
  sunLocalizedBloomStrength: number;
  sunSurfaceAnimationSpeed: number;
  sunPlasmaContrast: number;
  sunCoronaOpacity: number;
  sunCoronaScale: number;
  sunCoronaZoomOutOpacity: number;
  sunCoronaExtremeZoomOpacity: number;
  sunCoronaExtremeZoomScaleBoost: number;
  sunAnimatedCoronaOpacity: number;
  sunAnimatedCoronaScale: number;
  sunAnimatedCoronaSpeed: number;
  sunFocusMinimumCameraDistanceMultiplier: number;
  sunExtremeZoomBloomBoost: number;
  sunFarCameraIntensityMultiplier: number;
  sunFarCameraCoronaOpacityMultiplier: number;
  sunPlanetDazzleIntensity: number;
  sunPlanetDazzleSurfaceGain: number;
  sunGlobalBloomIntensity: number;
  sunGlobalBloomRadius: number;
  sunGlobalBloomThreshold: number;
  uiBloomIntensity: number;
  uiBloomRadius: number;
  uiBloomThreshold: number;
  planetBloomSourceGain: number;
  nodeBloomSourceGain: number;
  shipBloomSourceGain: number;
  sunPlanetInnerReflectionMultiplier: number;
  sunPlanetEarthReflectionMultiplier: number;
  sunPlanetOuterGlintMultiplier: number;
  planetRingGlintMultiplier: number;
  terminatorContrast: number;
  bodyNightSideDarkness: number;
  bodyDaySideBrightness: number;
  bodyRimLightIntensity: number;
  bodyDarkSilhouetteRimIntensity: number;
  bodyMaterialRoughness: number;
  bodyMaterialMetalness: number;
  earthNightGridIntensity: number;
  earthNightGridDensity: number;
  earthCloudOpacity: number;
  earthCloudAltitudeScale: number;
  earthCloudRotationSpeed: number;
  earthRotationSpeed: number;
  planetRotationSpeed: number;
  moonRotationSpeed: number;
  orbitRailOpacity: number;
  orbitRailGlow: number;
  orbitRailBacksideOpacity: number;
  orbitRailFocusBoost: number;
  orbitRailDistanceFade: number;
  orbitRailLineWidth: number;
  nodeRingOpacity: number;
  nodeRingGlow: number;
  nodeRingBacksideOpacity: number;
  nodeRingOccludedOpacity: number;
  nodeRingOcclusionRadiusMultiplier: number;
  nodeRingOcclusionFeather: number;
  nodeRingHoverIntensity: number;
  nodeRingSelectedPulse: number;
  nodeRingMinScreenSize: number;
  nodeRingLineWidth: number;
  tacticalUiScale: number;
  zoomOutUiBoost: number;
  zoomInUiBoost: number;
  emptyNodeOpacity: number;
  nodeRingMinPx: number;
  nodeRingMaxPx: number;
  occupiedNodeRingMinPx: number;
  occupiedNodeRingMaxPx: number;
  shipDotMinPx: number;
  shipDotGlowMinPx: number;
  shipDotGlowStrength: number;
  productiveMarkerMinPx: number;
  tritiumPipScale: number;
  tritiumPipZoomOutScale: number;
  tritiumPipZoomInScale: number;
  productiveMarkerZoomOutFlashFadeInMs: number;
  productiveMarkerZoomOutFlashHoldMs: number;
  productiveMarkerZoomOutFlashFadeOutMs: number;
  productiveMarkerZoomOutFlashOpacityBoost: number;
  productiveMarkerZoomOutFlashScaleBoost: number;
  nodeUnoccupiedColor: number;
  playerFactionColor: number;
  enemyFactionColor: number;
  playerOccupiedNodeRingWidthMultiplier: number;
  nodeUnoccupiedBandOpacity: number;
  playerOccupiedNodeBandWidthRatio: number;
  playerOccupiedNodeBandOpacity: number;
  playerOccupiedNodeRingOpacity: number;
  selectedNodeRingBoost: number;
  selectedNodeFinOpacity: number;
  shipMarkerSize: number;
  shipMarkerOpacity: number;
  shipModelScale: number;
  shipModelScreenPixels: number;
  shipModelCollapseDistance: number;
  orbitObjectZoomOutReadabilityBoost: number;
  orbitObjectZoomInReadabilityBoost: number;
  orbitObjectFormationSpacingScreenPixels: number;
  orbitObjectLargeBodyScreenRadiusStartPx: number;
  orbitObjectLargeBodyScreenRadiusEndPx: number;
  orbitObjectLargeBodyReadabilityBoost: number;
  shipOrbitAngularSpeed: number;
  shipDotPulseSpeed: number;
  shipDotScale: number;
  shipDotScreenPixels: number;
  shipLightBlinkFloor: number;
  shipLightBlinkBeatBoost: number;
  shipOrbitEngineGlowFloor: number;
  shipOrbitEngineGlowBeatBoost: number;
  shipOrbitEngineGlowScaleBoost: number;
  shipDriveWakeLength: number;
  shipDriveWakeRadius: number;
  shipDriveWakeOpacity: number;
  shipDriveWakeFilamentOpacity: number;
  shipDriveWakeZoomInTailFadeStart: number;
  shipDriveWakeZoomInTailFadeEnd: number;
  shipDriveWakeFlowStrength: number;
  shipDriveWakeFlowSpeed: number;
  shipDriveWakeCameraDazzleIntensity: number;
  shipDriveWakeCameraDazzleExposure: number;
  shipDriveWakeCameraDazzleBloomStrength: number;
  shipDriveWakeCameraDazzleZoomStart: number;
  shipDriveWakeCameraDazzleZoomEnd: number;
  shipDriveWakeCameraDazzleScreenLengthStart: number;
  shipDriveWakeCameraDazzleScreenLengthEnd: number;
  shipDriveWakeCameraDazzleProximityStart: number;
  shipDriveWakeCameraDazzleProximityEnd: number;
  constructionCargoMinScreenSeparationPixels: number;
  constructionCargoMaxAngularSpacing: number;
  constructionCargoZoomedOutScreenPixels: number;
  constructionCargoZoomedInScreenPixels: number;
  constructionCargoZoomOutReadabilityBoost: number;
  constructionCargoZoomInBeaconOpacity: number;
  shipProductionGlowScreenPixels: number;
  shipProductionGlowIntensity: number;
  shipProductionGlowRadius: number;
  burnPreviewColor: number;
  burnPreviewOpacity: number;
  burnPreviewThicknessMultiplier: number;
  burnPreviewEffectOpacity: number;
  burnPreviewEffectParticleCount: number;
  burnPreviewEffectParticleSizePixels: number;
  burnPreviewEffectApertureSizePixels: number;
  burnPreviewEffectFlowSpeed: number;
  burnTrajectoryZoomOutThicknessBoost: number;
  burnTrajectoryZoomOutThicknessDetailThreshold: number;
  pendingBurnOpacity: number;
  futureDestinationMarkerOpacity: number;
  activeBurnMarkerOpacity: number;
  fireMarkerColor: number;
  fireTargetDimOpacity: number;
  firePreviewOpacity: number;
  firePreviewEffectOpacity: number;
  firePreviewEffectParticleCount: number;
  firePreviewEffectParticleSizePixels: number;
  firePreviewEffectReticleSizePixels: number;
  firePreviewEffectFlowSpeed: number;
  confirmedOrderEffectOpacityMultiplier: number;
  confirmedOrderEffectParticleMultiplier: number;
  confirmedOrderEffectSizeMultiplier: number;
  fireConfirmedSolutionRevealDurationSeconds: number;
  fireConfirmedSolutionFadeDurationSeconds: number;
  fireConfirmedSolutionAimAcquireProgress: number;
  pendingFireOpacity: number;
  activeMissileOpacity: number;
  missileMarkerScreenPixels: number;
  missileMarkerExtremeZoomMinScreenPixels: number;
  missileMarkerZoomedInScreenPixels: number;
  missileImpactBodyFlashIntensity: number;
  missileImpactBodyFlashAfterglowIntensity: number;
  missileImpactBodyFlashRadius: number;
  missileImpactBodyFlashDurationSeconds: number;
  missileImpactBodyFlashColor: number;
  starCount: number;
  starBrightness: number;
  starSizeMin: number;
  starSizeMax: number;
  starFlickerAmount: number;
  starFlickerSpeed: number;
  starParallaxStrength: number;
  starLayerCount: number;
  tritiumPatternSpeed: number;
  tritiumPatternContrast: number;
  tritiumExtractionSweepSpeed: number;
  tritiumExtractionSweepArcRadians: number;
  tritiumExtractionSweepOpacity: number;
  tritiumExtractionStreamOpacity: number;
  tritiumExtractionCollectorOpacity: number;
  tritiumExtractionSurfaceGlowIntensity: number;
  tritiumExtractionSurfaceGlowRadiusMultiplier: number;
  tritiumExtractionSurfaceGlowColor: number;
  shipyardLightIntensity: number;
  shipyardLightFlicker: number;
  shipyardLightRhythmBpm: number;
  shipyardLightWorkerPulseBoost: number;
  shipyardLightSideOpacityFloor: number;
  shipyardDarkSideOpacityBoost: number;
  shipyardTerminatorGlowBoost: number;
  shipyardSurfaceCoverageRadius: number;
  shipyardGridCollapseDetailStart: number;
  shipyardGridCollapseDetailEnd: number;
  shipyardCollapsedGridMinPx: number;
  shipyardCollapsedGridMaxPx: number;
  receiverEclipseDarkness: number;
  receiverEclipseStrength: number;
  receiverEclipseFeather: number;
  receiverEclipseMinDiskRadius: number;
  shadowVolumeDarkness: number;
  shadowVolumeStrength: number;
  shadowVolumeTaper: number;
  shadowVolumeEdgeSoftness: number;
  physicalShadowConeOpacity: number;
  physicalShadowConeContrastOpacity: number;
  physicalShadowConeContrastColor: number;
  physicalShadowConeNearRadius: number;
  physicalShadowConeFarRadius: number;
  physicalShadowConeZoomInStartDetail: number;
  physicalShadowConeZoomInEndDetail: number;
  physicalShadowConeZoomInFarRadius: number;
  physicalShadowConeZoomInOpacityMultiplier: number;
  physicalShadowConeZoomInContrastOpacityMultiplier: number;
  physicalShadowConeZoomInCoreTailFadeStart: number;
  physicalShadowConeZoomInContrastTailFadeStart: number;
  physicalShadowConeZoomInTailFadeEnd: number;
  solarDustEnabled: boolean;
  solarDustOpacity: number;
  solarDustNoiseScale: number;
  solarDustNoiseSpeed: number;
  solarDustDitherStrength: number;
  solarDustSunFalloff: number;
  solarDustNearSunBoost: number;
  solarDustPeripheralBloom: number;
  solarDustPeripheralFloor: number;
  solarDustMaxBrightness: number;
  solarOcclusionEnabled: boolean;
  solarOcclusionOpacity: number;
  solarOcclusionLength: number;
  solarOcclusionWidth: number;
  solarOcclusionFade: number;
  solarOcclusionBodyRadiusMultiplier: number;
  solarOcclusionMinBodyRadius: number;
  solarOcclusionZoomFadeStart: number;
  solarOcclusionZoomFadeEnd: number;
  solarOcclusionCoronaIntensity: number;
  solarOcclusionExposureCompression: number;
  solarOcclusionReemergenceIntensity: number;
  solarOcclusionReemergenceDurationSeconds: number;
  solarOcclusionReemergenceArmCoverage: number;
  solarOcclusionReemergenceReleaseCoverage: number;
  atmosphericScatteringIntensity: number;
  atmosphericScatteringScale: number;
  atmosphericScatteringFalloff: number;
  atmosphericScatteringTerminatorBoost: number;
  heliocentricScaleBase: number;
  heliocentricScaleZoomOutCompression: number;
  heliocentricScaleZoomMultiplier: number;
  heliocentricScaleFocusMultiplier: number;
  localMoonScaleBase: number;
  localMoonScaleFocusMultiplier: number;
  localMoonScaleMax: number;
  planetDisplayRadiusMultiplier: number;
  planetDisplayRadiusMin: number;
  moonDisplayRadiusMultiplier: number;
  moonDisplayRadiusMin: number;
  bodyRadiusReference: number;
  bodyRadiusZoomOutExponent: number;
  bodyRadiusZoomInExponent: number;
  bodyRadiusZoomOutBoost: number;
  moonRadiusReference: number;
  moonRadiusZoomOutExponent: number;
  moonRadiusZoomInExponent: number;
  bodyScaleZoomExponent: number;
  sunDisplayRadiusBase: number;
  sunDisplayRadiusMin: number;
  sunDisplayRadiusMax: number;
  sunFocusScaleMultiplier: number;
  sunNonFocusScaleMultiplier: number;
  planetNodeRingScaleMultiplier: number;
  planetNodeRingMinRadius: number;
  planetNodeRingZoomInMinRadius: number;
  planetNodeScale: number;
  nodeRingMinScreenScale: number;
  nodeRingMaxScreenScale: number;
  bodyPickerScaleMultiplier: number;
  nodeOrbitPickerMargin: number;
  nodeOrbitPickerWidthRatio: number;
  moonNodeRingScaleMultiplier: number;
  moonNodeRingMinRadius: number;
  moonNodeRingZoomInMinRadius: number;
  moonNodeScale: number;
  moonNodeRingMinScreenScale: number;
  moonNodeRingZoomOutBoost: number;
  nodeRingMinGap: number;
  parentMoonNodeRingMinGap: number;
  panCloseSlowdownDistance: number;
  panCloseSlowdownMinimumMultiplier: number;
  panMinWorldUnitsPerPixel: number;
  panMaxWorldUnitsPerPixel: number;
  panMinVisibleSystemFraction: number;
  futureShipDisplayScale: number;
  focusPanDurationMs: number;
  turnAnimationDurationMs: number;
  turnAnimationEase: "smoothstep" | "smootherstep";
  turnAnimationDisableInputDuringTransition: boolean;
  turnAnimationAllowQueueNextTurn: boolean;
  extremeZoomUiFadeStartDetail: number;
  extremeZoomUiFadeEndDetail: number;
  extremeZoomUiFadeMinOpacity: number;
  extremeZoomNodeFadeStartDetail: number;
  extremeZoomNodeFadeEndDetail: number;
  extremeZoomNodeFadeMinOpacity: number;
  extremeZoomEdgeOnNodeFadeStartDetail: number;
  extremeZoomEdgeOnNodeFadeEndDetail: number;
  extremeZoomEdgeOnNodeFadeMinOpacity: number;
  labelMinScale: number;
  labelMaxScale: number;
  labelOpacity: number;
  labelFocusOpacity: number;
  labelDistanceFadeStart: number;
  labelDistanceFadeEnd: number;
  labelBackgroundOpacity: number;
  labelHoverBoost: number;
  toneMappingExposure: number;
  vignetteStrength: number;
  grainStrength: number;
}>;

export const legacyPhysicalShadowConeVisualTuning = {
  opacity: 0.46,
  contrastOpacity: 0.23,
  contrastColor: 0x0a0a0a,
  nearRadius: 1,
  farRadius: 0.08,
  coreTailFadeStart: 0.56,
  contrastTailFadeStart: 0.48,
  tailFadeEnd: 1
} as const;

export const defaultCinematic3dVisualTuning: Cinematic3dVisualTuning = {
  sunLightIntensity: 1.35,
  ambientLightIntensity: 0.018,
  sunBloomIntensity: 1.08,
  sunLocalizedBloomStrength: 0,
  sunSurfaceAnimationSpeed: 0.04,
  sunPlasmaContrast: 1.65,
  sunCoronaOpacity: 0.64,
  sunCoronaScale: 4.8,
  sunCoronaZoomOutOpacity: 0.64,
  sunCoronaExtremeZoomOpacity: 0.64,
  sunCoronaExtremeZoomScaleBoost: 0,
  sunAnimatedCoronaOpacity: 0.62,
  sunAnimatedCoronaScale: 0.98,
  sunAnimatedCoronaSpeed: 0.72,
  sunFocusMinimumCameraDistanceMultiplier: 5.2,
  sunExtremeZoomBloomBoost: 0,
  sunFarCameraIntensityMultiplier: 1,
  sunFarCameraCoronaOpacityMultiplier: 1,
  sunPlanetDazzleIntensity: 0.74,
  sunPlanetDazzleSurfaceGain: 2.05,
  // Keep the whole-frame bloom narrow and selective: only genuinely luminous surfaces and
  // markers should bleed into nearby space, without washing out rails or planetary detail.
  sunGlobalBloomIntensity: 0.27,
  sunGlobalBloomRadius: 0.06,
  sunGlobalBloomThreshold: 0.28,
  // Tactical/UI light should read as a tight emission fringe, not as a soft-focus filter.
  uiBloomIntensity: 0.11,
  uiBloomRadius: 0,
  uiBloomThreshold: 0.24,
  // The world pass contains only the illuminated limb of a planet. Give that narrow source
  // enough HDR headroom to survive extraction at the cinematic threshold without broadening UI.
  planetBloomSourceGain: 7,
  nodeBloomSourceGain: 1.9,
  // Keep ship hulls, lights, and drive wakes crisp in the direct render while allowing only a
  // restrained fraction of their energy into the bloom extraction pass.
  shipBloomSourceGain: 0.32,
  sunPlanetInnerReflectionMultiplier: 0.46,
  sunPlanetEarthReflectionMultiplier: 0.26,
  sunPlanetOuterGlintMultiplier: 0.22,
  planetRingGlintMultiplier: 1.4,
  terminatorContrast: 2.8,
  bodyNightSideDarkness: 0.022,
  bodyDaySideBrightness: 1.85,
  bodyRimLightIntensity: 0.025,
  bodyDarkSilhouetteRimIntensity: 0.17,
  bodyMaterialRoughness: 0.92,
  bodyMaterialMetalness: 0,
  earthNightGridIntensity: 0.71,
  earthNightGridDensity: 0.74,
  earthCloudOpacity: 0.82,
  earthCloudAltitudeScale: 1.018,
  earthCloudRotationSpeed: 0.058,
  earthRotationSpeed: 0.046,
  planetRotationSpeed: 0.028,
  moonRotationSpeed: 0.022,
  orbitRailOpacity: 0.2,
  orbitRailGlow: 0.34,
  orbitRailBacksideOpacity: 0.06,
  orbitRailFocusBoost: 1.65,
  orbitRailDistanceFade: 0.58,
  orbitRailLineWidth: 1,
  nodeRingOpacity: 0.46,
  nodeRingGlow: 0.2,
  nodeRingBacksideOpacity: 0.14,
  nodeRingOccludedOpacity: 0,
  nodeRingOcclusionRadiusMultiplier: 1.08,
  nodeRingOcclusionFeather: 0.18,
  nodeRingHoverIntensity: 0.24,
  nodeRingSelectedPulse: 0.16,
  nodeRingMinScreenSize: 40,
  nodeRingLineWidth: 1,
  tacticalUiScale: 1,
  zoomOutUiBoost: 1.45,
  zoomInUiBoost: 1,
  emptyNodeOpacity: 0.46,
  nodeRingMinPx: 1.2,
  nodeRingMaxPx: 1.55,
  occupiedNodeRingMinPx: 1.7,
  occupiedNodeRingMaxPx: 2.15,
  shipDotMinPx: 7.2,
  shipDotGlowMinPx: 8.6,
  shipDotGlowStrength: 0.18,
  productiveMarkerMinPx: 3.35,
  tritiumPipScale: 1.24,
  tritiumPipZoomOutScale: 2.55,
  tritiumPipZoomInScale: 1.12,
  productiveMarkerZoomOutFlashFadeInMs: 300,
  productiveMarkerZoomOutFlashHoldMs: 4600,
  productiveMarkerZoomOutFlashFadeOutMs: 1500,
  productiveMarkerZoomOutFlashOpacityBoost: 2.85,
  productiveMarkerZoomOutFlashScaleBoost: 0.68,
  nodeUnoccupiedColor: 0x80919d,
  playerFactionColor: 0x9fe8ff,
  enemyFactionColor: 0xc982ff,
  playerOccupiedNodeRingWidthMultiplier: 1.09,
  nodeUnoccupiedBandOpacity: 0.14,
  playerOccupiedNodeBandWidthRatio: 0.024,
  playerOccupiedNodeBandOpacity: 0.58,
  playerOccupiedNodeRingOpacity: 0.96,
  selectedNodeRingBoost: 0.18,
  selectedNodeFinOpacity: 0.92,
  shipMarkerSize: 0.64,
  shipMarkerOpacity: 0.95,
  shipModelScale: 1,
  shipModelScreenPixels: 12.8,
  shipModelCollapseDistance: 900,
  orbitObjectZoomOutReadabilityBoost: 1.28,
  orbitObjectZoomInReadabilityBoost: 1.04,
  orbitObjectFormationSpacingScreenPixels: 42,
  orbitObjectLargeBodyScreenRadiusStartPx: 140,
  orbitObjectLargeBodyScreenRadiusEndPx: 420,
  orbitObjectLargeBodyReadabilityBoost: 2.3,
  shipOrbitAngularSpeed: 0.22,
  shipDotPulseSpeed: 2.4,
  shipDotScale: 1.18,
  shipDotScreenPixels: 7.8,
  shipLightBlinkFloor: 0.16,
  shipLightBlinkBeatBoost: 0.84,
  shipOrbitEngineGlowFloor: 0.36,
  shipOrbitEngineGlowBeatBoost: 0.28,
  shipOrbitEngineGlowScaleBoost: 0.12,
  shipDriveWakeLength: 42,
  shipDriveWakeRadius: 0.13,
  shipDriveWakeOpacity: 0.22,
  shipDriveWakeFilamentOpacity: 0.5,
  shipDriveWakeZoomInTailFadeStart: 0.08,
  shipDriveWakeZoomInTailFadeEnd: 0.64,
  shipDriveWakeFlowStrength: 0.2,
  shipDriveWakeFlowSpeed: 2.4,
  shipDriveWakeCameraDazzleIntensity: 1,
  shipDriveWakeCameraDazzleExposure: 1.1,
  shipDriveWakeCameraDazzleBloomStrength: 1.8,
  shipDriveWakeCameraDazzleZoomStart: 1.02,
  shipDriveWakeCameraDazzleZoomEnd: 1.16,
  shipDriveWakeCameraDazzleScreenLengthStart: 90,
  shipDriveWakeCameraDazzleScreenLengthEnd: 280,
  shipDriveWakeCameraDazzleProximityStart: 3,
  shipDriveWakeCameraDazzleProximityEnd: 18,
  constructionCargoMinScreenSeparationPixels: 68,
  constructionCargoMaxAngularSpacing: 1.02,
  constructionCargoZoomedOutScreenPixels: 18.8,
  constructionCargoZoomedInScreenPixels: 25.4,
  constructionCargoZoomOutReadabilityBoost: 1.62,
  constructionCargoZoomInBeaconOpacity: 0.95,
  shipProductionGlowScreenPixels: 22,
  shipProductionGlowIntensity: 0.5,
  shipProductionGlowRadius: 165,
  burnPreviewColor: 0x9fe8ff,
  burnPreviewOpacity: 0.74,
  burnPreviewThicknessMultiplier: 2.25,
  burnPreviewEffectOpacity: 0.9,
  burnPreviewEffectParticleCount: 36,
  burnPreviewEffectParticleSizePixels: 6.8,
  burnPreviewEffectApertureSizePixels: 38,
  burnPreviewEffectFlowSpeed: 0.24,
  burnTrajectoryZoomOutThicknessBoost: 1.58,
  burnTrajectoryZoomOutThicknessDetailThreshold: 0.22,
  pendingBurnOpacity: 0.84,
  futureDestinationMarkerOpacity: 0.66,
  activeBurnMarkerOpacity: 0.92,
  fireMarkerColor: 0xff2638,
  fireTargetDimOpacity: 0.2,
  firePreviewOpacity: 0.82,
  firePreviewEffectOpacity: 0.96,
  firePreviewEffectParticleCount: 42,
  firePreviewEffectParticleSizePixels: 8.2,
  firePreviewEffectReticleSizePixels: 48,
  firePreviewEffectFlowSpeed: 0.42,
  confirmedOrderEffectOpacityMultiplier: 0.56,
  confirmedOrderEffectParticleMultiplier: 0.54,
  confirmedOrderEffectSizeMultiplier: 0.82,
  fireConfirmedSolutionRevealDurationSeconds: 0.82,
  fireConfirmedSolutionFadeDurationSeconds: 0.18,
  fireConfirmedSolutionAimAcquireProgress: 0.58,
  pendingFireOpacity: 0.74,
  activeMissileOpacity: 0.96,
  missileMarkerScreenPixels: 8.6,
  missileMarkerExtremeZoomMinScreenPixels: 3.2,
  missileMarkerZoomedInScreenPixels: 16.8,
  missileImpactBodyFlashIntensity: 11.8,
  missileImpactBodyFlashAfterglowIntensity: 0,
  missileImpactBodyFlashRadius: 880,
  missileImpactBodyFlashDurationSeconds: 0.44,
  missileImpactBodyFlashColor: 0xf5fdff,
  starCount: 768,
  starBrightness: 1,
  starSizeMin: 6,
  starSizeMax: 8,
  starFlickerAmount: 0.18,
  starFlickerSpeed: 1.08,
  starParallaxStrength: 0.0012,
  starLayerCount: 3,
  tritiumPatternSpeed: 0.026,
  tritiumPatternContrast: 0.78,
  tritiumExtractionSweepSpeed: 0.74,
  tritiumExtractionSweepArcRadians: 0.5,
  tritiumExtractionSweepOpacity: 0.28,
  tritiumExtractionStreamOpacity: 1,
  tritiumExtractionCollectorOpacity: 0.86,
  tritiumExtractionSurfaceGlowIntensity: 0,
  tritiumExtractionSurfaceGlowRadiusMultiplier: 1.35,
  tritiumExtractionSurfaceGlowColor: 0x9fefff,
  shipyardLightIntensity: 0.74,
  shipyardLightFlicker: 0.035,
  shipyardLightRhythmBpm: 5,
  shipyardLightWorkerPulseBoost: 0.28,
  shipyardLightSideOpacityFloor: 0.12,
  shipyardDarkSideOpacityBoost: 1.14,
  shipyardTerminatorGlowBoost: 0.2,
  shipyardSurfaceCoverageRadius: 0.92,
  shipyardGridCollapseDetailStart: 0.86,
  shipyardGridCollapseDetailEnd: 0.48,
  shipyardCollapsedGridMinPx: 8.8,
  shipyardCollapsedGridMaxPx: 12.4,
  receiverEclipseDarkness: 0.56,
  receiverEclipseStrength: 1,
  receiverEclipseFeather: 0.004,
  receiverEclipseMinDiskRadius: 0.07,
  shadowVolumeDarkness: 0.46,
  shadowVolumeStrength: 1,
  shadowVolumeTaper: 0.012,
  shadowVolumeEdgeSoftness: 0.36,
  physicalShadowConeOpacity: legacyPhysicalShadowConeVisualTuning.opacity,
  physicalShadowConeContrastOpacity: legacyPhysicalShadowConeVisualTuning.contrastOpacity,
  physicalShadowConeContrastColor: legacyPhysicalShadowConeVisualTuning.contrastColor,
  physicalShadowConeNearRadius: legacyPhysicalShadowConeVisualTuning.nearRadius,
  physicalShadowConeFarRadius: legacyPhysicalShadowConeVisualTuning.farRadius,
  physicalShadowConeZoomInStartDetail: 0.22,
  physicalShadowConeZoomInEndDetail: 1,
  physicalShadowConeZoomInFarRadius: 1,
  physicalShadowConeZoomInOpacityMultiplier: 0.46,
  physicalShadowConeZoomInContrastOpacityMultiplier: 0.52,
  physicalShadowConeZoomInCoreTailFadeStart: 0.34,
  physicalShadowConeZoomInContrastTailFadeStart: 0.3,
  physicalShadowConeZoomInTailFadeEnd: 0.84,
  solarDustEnabled: true,
  solarDustOpacity: 0.024,
  solarDustNoiseScale: 5,
  solarDustNoiseSpeed: 0.035,
  solarDustDitherStrength: 0.18,
  solarDustSunFalloff: 1.18,
  solarDustNearSunBoost: 0.12,
  solarDustPeripheralBloom: 0.08,
  solarDustPeripheralFloor: 0.08,
  solarDustMaxBrightness: 0.18,
  solarOcclusionEnabled: true,
  solarOcclusionOpacity: 0.95,
  solarOcclusionLength: 7.5,
  solarOcclusionWidth: 0.4,
  solarOcclusionFade: 0.58,
  solarOcclusionBodyRadiusMultiplier: 1,
  solarOcclusionMinBodyRadius: 1.5,
  solarOcclusionZoomFadeStart: 1200,
  solarOcclusionZoomFadeEnd: 2600,
  solarOcclusionCoronaIntensity: 0.34,
  solarOcclusionExposureCompression: 0.18,
  solarOcclusionReemergenceIntensity: 0.28,
  solarOcclusionReemergenceDurationSeconds: 0.48,
  solarOcclusionReemergenceArmCoverage: 0.82,
  solarOcclusionReemergenceReleaseCoverage: 0.68,
  atmosphericScatteringIntensity: 0.62,
  atmosphericScatteringScale: 1.035,
  atmosphericScatteringFalloff: 3.6,
  atmosphericScatteringTerminatorBoost: 0.48,
  heliocentricScaleBase: 1.72,
  heliocentricScaleZoomOutCompression: 0.68,
  heliocentricScaleZoomMultiplier: 3.3,
  heliocentricScaleFocusMultiplier: 1.65,
  localMoonScaleBase: 0.84,
  localMoonScaleFocusMultiplier: 1.2,
  localMoonScaleMax: 1.05,
  planetDisplayRadiusMultiplier: 2,
  planetDisplayRadiusMin: 18.5,
  moonDisplayRadiusMultiplier: 0.55,
  moonDisplayRadiusMin: 3.3,
  bodyRadiusReference: 9,
  bodyRadiusZoomOutExponent: 0.64,
  bodyRadiusZoomInExponent: 1.18,
  bodyRadiusZoomOutBoost: 0.22,
  moonRadiusReference: 3,
  moonRadiusZoomOutExponent: 0.82,
  moonRadiusZoomInExponent: 1.08,
  bodyScaleZoomExponent: 1.35,
  sunDisplayRadiusBase: 32,
  sunDisplayRadiusMin: 19,
  sunDisplayRadiusMax: 64,
  sunFocusScaleMultiplier: 1.7,
  sunNonFocusScaleMultiplier: 0.72,
  planetNodeRingScaleMultiplier: 1.38,
  planetNodeRingMinRadius: 44,
  planetNodeRingZoomInMinRadius: 31,
  planetNodeScale: 1.32,
  nodeRingMinScreenScale: 1.1,
  nodeRingMaxScreenScale: 4.8,
  bodyPickerScaleMultiplier: 1.55,
  nodeOrbitPickerMargin: 1.8,
  nodeOrbitPickerWidthRatio: 0.11,
  moonNodeRingScaleMultiplier: 1.06,
  moonNodeRingMinRadius: 40,
  moonNodeRingZoomInMinRadius: 22,
  moonNodeScale: 1.03,
  moonNodeRingMinScreenScale: 1.28,
  moonNodeRingZoomOutBoost: 0.12,
  nodeRingMinGap: 12,
  parentMoonNodeRingMinGap: 20,
  panCloseSlowdownDistance: 280,
  panCloseSlowdownMinimumMultiplier: 0.28,
  panMinWorldUnitsPerPixel: 0.025,
  panMaxWorldUnitsPerPixel: 2.8,
  panMinVisibleSystemFraction: 0.72,
  futureShipDisplayScale: 0.8,
  focusPanDurationMs: 320,
  turnAnimationDurationMs: 1150,
  turnAnimationEase: "smootherstep",
  turnAnimationDisableInputDuringTransition: true,
  turnAnimationAllowQueueNextTurn: false,
  extremeZoomUiFadeStartDetail: 0.72,
  extremeZoomUiFadeEndDetail: 0.98,
  extremeZoomUiFadeMinOpacity: 0.34,
  extremeZoomNodeFadeStartDetail: 0.54,
  extremeZoomNodeFadeEndDetail: 1,
  extremeZoomNodeFadeMinOpacity: 1,
  extremeZoomEdgeOnNodeFadeStartDetail: 0.82,
  extremeZoomEdgeOnNodeFadeEndDetail: 1,
  extremeZoomEdgeOnNodeFadeMinOpacity: 1,
  labelMinScale: 1.04,
  labelMaxScale: 1.34,
  labelOpacity: 0.78,
  labelFocusOpacity: 1,
  labelDistanceFadeStart: 420,
  labelDistanceFadeEnd: 1200,
  labelBackgroundOpacity: 0.38,
  labelHoverBoost: 0.2,
  toneMappingExposure: 1.05,
  vignetteStrength: 0,
  grainStrength: 0.035
};

export function mergeCinematic3dTuning(
  overrides: Partial<Cinematic3dVisualTuning> = {}
): Cinematic3dVisualTuning {
  return {
    ...defaultCinematic3dVisualTuning,
    ...overrides
  };
}

/**
 * Keeps the current extreme-zoom marker size for a missile at T-1, then reduces
 * it in inverse proportion to its remaining flight time. The floor leaves even
 * a T-7 missile as a deliberate, readable dot rather than a single pixel.
 */
export function getExtremeZoomMissileMarkerScreenPixels(
  tuning: Pick<
    Cinematic3dVisualTuning,
    "missileMarkerScreenPixels" | "missileMarkerExtremeZoomMinScreenPixels"
  >,
  remainingTurns: number
): number {
  const t1ScreenPixels = tuning.missileMarkerScreenPixels * 0.78;
  const normalizedRemainingTurns = Math.max(1, Math.ceil(remainingTurns));

  return Math.max(
    tuning.missileMarkerExtremeZoomMinScreenPixels,
    t1ScreenPixels / normalizedRemainingTurns
  );
}
