import type { TutorialRuntimeState } from "./runtimeTypes";

export function createTutorialRuntimeState(options: {
  startedAt: number;
  shipyardLessonNodeId: string;
}): TutorialRuntimeState {
  return {
    segmentId: "TUTORIAL_SEGMENT_01",
    phase: "awaitingInitialSelection",
    startedAt: options.startedAt,
    firstSelectionAt: null,
    firstBurnReselectionStartedAt: null,
    inputLocked: false,
    autoAdvanceActive: false,
    activeMandatoryLaunchId: null,
    mandatoryLaunchResumePhase: null,
    enemySimpleAiEnabled: false,
    hasZoomedOutCamera: false,
    firstBurnPreviewDestinationNodeId: null,
    firstBurnDestinationNodeId: null,
    firstBurnArrivalTurn: null,
    productiveBurnOriginNodeId: null,
    productiveBurnDestinationNodeId: null,
    productiveBurnArrivalTurn: null,
    productiveBurnPromptStartedAt: null,
    productiveBurnReselectionStartedAt: null,
    tutorialBurnDestinationNodeId: null,
    tutorialBurnArrivalTurn: null,
    tritiumAnchorNodeId: null,
    hasIntroducedBarren: false,
    tritiumLessonContinuation: null,
    shipyardContestedRecoveryActive: false,
    shipyardSupportProductionNodeId: null,
    shipyardLessonNodeId: options.shipyardLessonNodeId,
    shipyardEnemyOriginNodeId: null,
    shipyardEnemyDestinationNodeId: null,
    shipyardEnemyFireImpactTurn: null,
    shipyardEnemyEvadeObserved: false,
    shipyardEnemyReturnArrivalTurn: null,
    shipyardPlayerEscapeNodeId: null,
    shipyardSupportFireNodeId: null,
    shipyardCounterContestOriginNodeId: null,
    shipyardCounterContestArrivalTurn: null,
    shipyardCounterContestAutoAdvanceConsumed: false,
    shipyardFirePromptStartedAt: null,
    shipyardSupportFirePromptStartedAt: null,
    shipyardContestedPromptStartedAt: null,
    enemyNodeId: null,
    evadeLessonMissileTargetNodeId: null,
    contestedNodeId: null,
    defensivePlayerNodeId: null,
    defensiveEscapeNodeId: null,
    defensiveMissileImpactTurn: null,
    firstEnemyKillReplayEventId: null,
    firstEnemyKillReplayNodeId: null,
    firstEnemyKillReplayWarningPending: false,
    cameraZoomFocusHintDisplayCount: 0,
    cameraZoomFocusHintVisible: false,
    cameraPanOrbitHintDisplayCount: 0,
    cameraPanOrbitHintVisible: false,
    timers: [],
    loggedKeys: new Set()
  };
}
